FROM ros:iron

# Source ROS 2 setup script
SHELL ["/bin/bash", "-c"]


ARG USERNAME=eva_sean
ARG HOMEPATH=/home/${USERNAME}/ub1_home
ARG GIT_USER=Sean053047
ARG GIT_EMAIL=sadlamb910803@gmail.com

RUN apt-get update
RUN apt-get update && \
    apt-get install -y tmux vim wget git curl htop nvtop gpg pip zsh

RUN mkdir -p ${HOMEPATH}/setup && mkdir -p ${HOMEPATH}/test
COPY *.sh ${HOMEPATH}/setup/
COPY ./file/.bashrc ${HOMEPATH}/.bashrc
COPY ./file/.zshrc ${HOMEPATH}/.zshrc
COPY ./file/.tmux.conf ${HOMEPATH}/.tmux.conf
COPY ./file/.p10k.zsh ${HOMEPATH}/.p10k.zsh
COPY ./file/. ${HOMEPATH}/test/

RUN bash ${HOMEPATH}/setup/install_tools_docker.sh --git_user ${GIT_USER} --git_email ${GIT_EMAIL} && \
    bash ${HOMEPATH}/setup/install_venv_related.sh

WORKDIR ${HOMEPATH}

# ENTRYPOINT ["zsh"]


