FROM ros:iron
ARG USERNAME=eva_sean
# Source ROS 2 setup script
SHELL ["/bin/bash", "-c"]

# RUN apt-get update
RUN apt-get update && \
    apt-get install -y tmux vim wget git curl htop nvtop gpg pip zsh 

RUN mkdir -p /setup && mkdir -p /home/${USERNAME}
COPY *.sh /setup/
COPY file/.* /home/${USERNAME}/

# WORKDIR  /home/${USERNAME}
RUN bash /setup/install_tools_docker.sh --git_user Sean053047 --git_email sadlamb910803@gmail.com && \
    bash /setup/install_venv_related.sh

WORKDIR /home/${USERNAME}

CMD ['zsh']