FROM nvidia/cuda:12.8.0-runtime-ubuntu22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    wget bzip2 htop \
    nvtop zsh ca-certificates \
    git tmux vim sudo \
    openssh-server \
    net-tools 
    # && rm -rf /var/lib/apt/lists/*

ARG UNAME=user
ARG UID=1000
ARG GID=1000
ARG GIT_USER=Sean053047
ARG GIT_MAIL=sadlamb910803@gmail.com
# Add new user
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -s /bin/zsh $UNAME
RUN echo "$UNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Setup ssh setting
RUN sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
# CMD ["/usr/bin/sshd", "-D"]
EXPOSE 20000

USER $UNAME


# Install Miniconda
RUN mkdir -p ~/miniconda3 && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
    rm ~/miniconda3/miniconda.sh
ENV CONDA_PKGS_ACCEPT_TERMS=true


# Add conda to path
ENV PATH="/home/$UNAME/miniconda3/bin:$PATH"

COPY --chown=$UID:$GID setup_ubuntu/install_tools_docker.sh "/home/$UNAME/setting/install_tools_docker.sh"
COPY --chown=$UID:$GID file/.tmux.conf "/home/$UNAME/.tmux.conf"
COPY --chown=$UID:$GID file/.p10k.zsh "/home/$UNAME/.p10k.zsh"
RUN  bash /home/$UNAME/setting/install_tools_docker.sh --git_user $GIT_USER --git_email $GIT_MAIL
RUN echo "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh" >> /home/$UNAME/.zshrc && \
    echo  '\nexport LANG=C.UTF-8' >> /home/$UNAME/.zshrc && \
    echo  '\nexport LC_ALL=C.UTF-8' >> /home/$UNAME/.zshrc
    
CMD ["/bin/zsh"]

